/*
  Warnings:

  - Added the required column `paymentFrequency` to the `InsuranceRecord` table without a default value. This is not possible if the table is not empty.
  - Added the required column `policyType` to the `InsuranceRecord` table without a default value. This is not possible if the table is not empty.
  - Added the required column `updatedAt` to the `InsuranceRecord` table without a default value. This is not possible if the table is not empty.
  - Added the required column `countryCode` to the `RegistrationRecord` table without a default value. This is not possible if the table is not empty.
  - Added the required column `updatedAt` to the `RegistrationRecord` table without a default value. This is not possible if the table is not empty.
  - Made the column `regNumber` on table `RegistrationRecord` required. This step will fail if there are existing NULL values in that column.

*/
-- AlterTable
ALTER TABLE "InsuranceRecord" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "currency" TEXT NOT NULL DEFAULT 'AUD',
ADD COLUMN     "notes" TEXT,
ADD COLUMN     "paymentFrequency" TEXT NOT NULL,
ADD COLUMN     "policyType" TEXT NOT NULL,
ADD COLUMN     "startDate" TIMESTAMP(3),
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL,
ALTER COLUMN "premiumAmount" SET DATA TYPE DECIMAL(12,2);

-- AlterTable
ALTER TABLE "RegistrationRecord" ADD COLUMN     "countryCode" TEXT NOT NULL,
ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "durationMonths" INTEGER,
ADD COLUMN     "issueDate" TIMESTAMP(3),
ADD COLUMN     "notes" TEXT,
ADD COLUMN     "region" TEXT,
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL,
ALTER COLUMN "regNumber" SET NOT NULL,
ALTER COLUMN "cost" SET DATA TYPE DECIMAL(12,2);

-- AlterTable
ALTER TABLE "Reminder" ADD COLUMN     "autoGenerated" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "sourceId" TEXT,
ADD COLUMN     "sourceType" TEXT;
