import { IsString, IsNotEmpty, IsDate, IsOptional, IsEnum, IsBoolean } from 'class-validator';
import { Type } from 'class-transformer';
import { ReminderSourceType } from '@prisma/client';

export enum ReminderStatus {
  OPEN = 'open',
  DONE = 'done',
  DISMISSED = 'dismissed',
}

export class CreateReminderDto {
  @IsString()
  @IsNotEmpty()
  title: string;

  @Type(() => Date)
  @IsDate()
  @IsNotEmpty()
  dueDate: Date;

  @IsString()
  @IsOptional()
  type?: string;

  @IsEnum(ReminderStatus)
  @IsOptional()
  status?: ReminderStatus;

  @IsString()
  @IsOptional()
  notes?: string;

  @IsString()
  @IsOptional()
  sourceId?: string;

  @IsEnum(ReminderSourceType)
  @IsOptional()
  sourceType?: ReminderSourceType;

  @IsBoolean()
  @IsOptional()
  autoGenerated?: boolean;
}
